name: model_deployment_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - torch>=1.8.0
      - torchvision>=0.9.0
      - azureml-defaults
      - azureml-core
      - pillow>=10.3.0
      - numpy>=1.23.5
      - requests>=2.32.0
      - pyyaml>=5.3.1
      - ultralytics>=8.2.34
      - azureml-inference-server-http
      - pandas>=1.1.4
      - gitpython>=3.1.30
